spring:
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  datasource:
#    url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver


  shardingsphere:
    datasource:
      enabled: true
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: 123456
    props:
      # 日志显示 SQL
      sql.show: true
    sharding:
      tables:
        # 订单表基础表
        t_order:
          # 真实表
          actualDataNodes: ds$->{0..1}.t_order_$->{0..1} # 映射节点
          # 分库策略
          databaseStrategy:
            standard:
              sharding-column: order_id # 生成的sharding-column需要再sql执行的时候有值，否则执行不成功，但是在
              preciseAlgorithmClassName: com.lin.sharding.infra.algorithm.MyDsPreciseAlgorithm #精确分片算法类名称，用于=和IN。。该类需实现PreciseShardingAlgorithm接口并提供无参数的构造器
              rangeAlgorithmClassName: com.lin.sharding.infra.algorithm.MyDsRangeAlgorithm #范围分片算法类名称，用于BETWEEN，可选。。该类需实现RangeShardingAlgorithm接口并提供无参数的构造器
          # 分表策略
          tableStrategy:
            standard:
              sharding-column: order_id # 生成的sharding-column需要再sql执行的时候有值，否则执行不成功，但是在
              preciseAlgorithmClassName: com.lin.sharding.infra.algorithm.MyTablePreciseAlgorithm #精确分片算法类名称，用于=和IN。。该类需实现PreciseShardingAlgorithm接口并提供无参数的构造器
              rangeAlgorithmClassName: com.lin.sharding.infra.algorithm.MyTableRangeAlgorithm #范围分片算法类名称，用于BETWEEN，可选。。该类需实现RangeShardingAlgorithm接口并提供无参数的构造器

mybatis:
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
    - classpath*:/mapper/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: ${MYBATIS_DEFAULT_STATEMENT_TIMEOUT:120}
    call-setters-on-nulls: true

logging:
  level:
    com.lin: debug
